# Form implementation generated from reading ui file 'src/gestore_password/ui/ui_login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(457, 346)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_slbl_titolo = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.login_slbl_titolo.setFont(font)
        self.login_slbl_titolo.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.login_slbl_titolo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.login_slbl_titolo.setObjectName("login_slbl_titolo")
        self.verticalLayout.addWidget(self.login_slbl_titolo)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_4.setSpacing(27)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.login_slbl_utente = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_slbl_utente.setFont(font)
        self.login_slbl_utente.setObjectName("login_slbl_utente")
        self.horizontalLayout_4.addWidget(self.login_slbl_utente)
        self.login_edit_utente = QtWidgets.QLineEdit(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_edit_utente.setFont(font)
        self.login_edit_utente.setObjectName("login_edit_utente")
        self.horizontalLayout_4.addWidget(self.login_edit_utente)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_slbl_password = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_slbl_password.setFont(font)
        self.login_slbl_password.setObjectName("login_slbl_password")
        self.horizontalLayout.addWidget(self.login_slbl_password)
        self.login_edit_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_edit_password.setFont(font)
        self.login_edit_password.setText("")
        self.login_edit_password.setObjectName("login_edit_password")
        self.horizontalLayout.addWidget(self.login_edit_password)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.login_btn_login = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_btn_login.setFont(font)
        self.login_btn_login.setObjectName("login_btn_login")
        self.horizontalLayout_5.addWidget(self.login_btn_login)
        self.login_btn_registrati = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_btn_registrati.setFont(font)
        self.login_btn_registrati.setObjectName("login_btn_registrati")
        self.horizontalLayout_5.addWidget(self.login_btn_registrati)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Log in"))
        self.login_slbl_titolo.setText(_translate("MainWindow", "LOG IN"))
        self.login_slbl_utente.setText(_translate("MainWindow", "Utente"))
        self.login_slbl_password.setText(_translate("MainWindow", "Password"))
        self.login_btn_login.setText(_translate("MainWindow", "Log in"))
        self.login_btn_registrati.setText(_translate("MainWindow", "Registrati"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
