# Form implementation generated from reading ui file 'ui/ui_login.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Login.sizePolicy().hasHeightForWidth())
        Login.setSizePolicy(sizePolicy)
        Login.setMinimumSize(QtCore.QSize(400, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(Login)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_slbl_titolo = QtWidgets.QLabel(parent=Login)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.login_slbl_titolo.setFont(font)
        self.login_slbl_titolo.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.login_slbl_titolo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.login_slbl_titolo.setObjectName("login_slbl_titolo")
        self.verticalLayout.addWidget(self.login_slbl_titolo)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_4.setSpacing(27)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.login_slbl_utente = QtWidgets.QLabel(parent=Login)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_slbl_utente.setFont(font)
        self.login_slbl_utente.setObjectName("login_slbl_utente")
        self.horizontalLayout_4.addWidget(self.login_slbl_utente)
        self.login_edit_utente = QtWidgets.QLineEdit(parent=Login)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_edit_utente.setFont(font)
        self.login_edit_utente.setObjectName("login_edit_utente")
        self.horizontalLayout_4.addWidget(self.login_edit_utente)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_slbl_password = QtWidgets.QLabel(parent=Login)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_slbl_password.setFont(font)
        self.login_slbl_password.setObjectName("login_slbl_password")
        self.horizontalLayout.addWidget(self.login_slbl_password)
        self.login_edit_password = QtWidgets.QLineEdit(parent=Login)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_edit_password.setFont(font)
        self.login_edit_password.setText("")
        self.login_edit_password.setObjectName("login_edit_password")
        self.horizontalLayout.addWidget(self.login_edit_password)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.login_btn_login = QtWidgets.QPushButton(parent=Login)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_btn_login.setFont(font)
        self.login_btn_login.setObjectName("login_btn_login")
        self.horizontalLayout_5.addWidget(self.login_btn_login)
        self.login_btn_registrati = QtWidgets.QPushButton(parent=Login)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_btn_registrati.setFont(font)
        self.login_btn_registrati.setObjectName("login_btn_registrati")
        self.horizontalLayout_5.addWidget(self.login_btn_registrati)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.login_slbl_titolo.setText(_translate("Login", "LOG IN"))
        self.login_slbl_utente.setText(_translate("Login", "Utente"))
        self.login_slbl_password.setText(_translate("Login", "Password"))
        self.login_btn_login.setText(_translate("Login", "Log in"))
        self.login_btn_registrati.setText(_translate("Login", "Registrati"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec())
