# Form implementation generated from reading ui file 'ui/ui_aggiungi_servizio.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Aggiungi(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(403, 356)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.aser_slbl_nome = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.aser_slbl_nome.setFont(font)
        self.aser_slbl_nome.setObjectName("aser_slbl_nome")
        self.horizontalLayout.addWidget(self.aser_slbl_nome)
        self.aser_edit_nome = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.aser_edit_nome.setFont(font)
        self.aser_edit_nome.setObjectName("aser_edit_nome")
        self.horizontalLayout.addWidget(self.aser_edit_nome)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(40)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.aser_slbl_user = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.aser_slbl_user.setFont(font)
        self.aser_slbl_user.setObjectName("aser_slbl_user")
        self.horizontalLayout_2.addWidget(self.aser_slbl_user)
        self.aser_edit_user = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.aser_edit_user.setFont(font)
        self.aser_edit_user.setObjectName("aser_edit_user")
        self.horizontalLayout_2.addWidget(self.aser_edit_user)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(45)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.aser_slbl_password = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.aser_slbl_password.setFont(font)
        self.aser_slbl_password.setObjectName("aser_slbl_password")
        self.horizontalLayout_3.addWidget(self.aser_slbl_password)
        self.aser_edit_password = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.aser_edit_password.setFont(font)
        self.aser_edit_password.setObjectName("aser_edit_password")
        self.horizontalLayout_3.addWidget(self.aser_edit_password)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.aser_dlg_btns = QtWidgets.QDialogButtonBox(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.aser_dlg_btns.setFont(font)
        self.aser_dlg_btns.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.aser_dlg_btns.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel | QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.aser_dlg_btns.setObjectName("aser_dlg_btns")
        self.verticalLayout_2.addWidget(self.aser_dlg_btns)

        self.retranslateUi(Dialog)
        self.aser_dlg_btns.accepted.connect(Dialog.accept)  # type: ignore
        self.aser_dlg_btns.rejected.connect(Dialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Aggiungi servizio"))
        self.aser_slbl_nome.setText(_translate("Dialog", "Nome servizio"))
        self.aser_slbl_user.setText(_translate("Dialog", "Username"))
        self.aser_slbl_password.setText(_translate("Dialog", "Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog_Aggiungi()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
