# Form implementation generated from reading ui file 'ui/ui_principale.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(823, 576)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Main.sizePolicy().hasHeightForWidth())
        Main.setSizePolicy(sizePolicy)
        Main.setMinimumSize(QtCore.QSize(600, 400))

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Main)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # TabWidget
        self.tabWidget = QtWidgets.QTabWidget(parent=Main)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")

        # ==================== TAB 1 - SERVIZI ====================
        self.main_tab1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.main_tab1.sizePolicy().hasHeightForWidth())
        self.main_tab1.setSizePolicy(sizePolicy)
        self.main_tab1.setObjectName("main_tab1")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_tab1)
        self.verticalLayout_3.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.main_vlay_tab1 = QtWidgets.QVBoxLayout()
        self.main_vlay_tab1.setSpacing(10)
        self.main_vlay_tab1.setObjectName("main_vlay_tab1")

        # Barra ricerca
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.main_edit_cerca = QtWidgets.QLineEdit(parent=self.main_tab1)
        self.main_edit_cerca.setMinimumHeight(30)
        self.main_edit_cerca.setObjectName("main_edit_cerca")
        self.horizontalLayout.addWidget(self.main_edit_cerca)

        self.main_btn_cerca = QtWidgets.QPushButton(parent=self.main_tab1)
        self.main_btn_cerca.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.main_btn_cerca.setMinimumSize(QtCore.QSize(30, 30))
        self.main_btn_cerca.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/cerca.png"),
                       QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.main_btn_cerca.setIcon(icon)
        self.main_btn_cerca.setObjectName("main_btn_cerca")
        self.horizontalLayout.addWidget(self.main_btn_cerca)

        spacerItem = QtWidgets.QSpacerItem(
            40, 20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)

        self.main_btn_aggiungi = QtWidgets.QPushButton(parent=self.main_tab1)
        self.main_btn_aggiungi.setMinimumHeight(30)
        self.main_btn_aggiungi.setObjectName("main_btn_aggiungi")
        self.horizontalLayout.addWidget(self.main_btn_aggiungi)

        self.main_vlay_tab1.addLayout(self.horizontalLayout)

        # Tabella servizi
        self.main_tbl_servizi = QtWidgets.QTableWidget(parent=self.main_tab1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        self.main_tbl_servizi.setSizePolicy(sizePolicy)
        self.main_tbl_servizi.setObjectName("main_tbl_servizi")
        self.main_tbl_servizi.setColumnCount(0)
        self.main_tbl_servizi.setRowCount(0)
        self.main_vlay_tab1.addWidget(self.main_tbl_servizi)

        self.verticalLayout_3.addLayout(self.main_vlay_tab1)
        self.tabWidget.addTab(self.main_tab1, "")

        # ==================== TAB 2 - PROFILO ====================
        self.main_tab_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.main_tab_2.sizePolicy().hasHeightForWidth())
        self.main_tab_2.setSizePolicy(sizePolicy)
        self.main_tab_2.setObjectName("main_tab_2")

        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.main_tab_2)
        self.verticalLayout_5.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_5.setSpacing(15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")

        # Spacer superiore
        spacerTopTab2 = QtWidgets.QSpacerItem(
            20, 40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.verticalLayout_5.addItem(spacerTopTab2)

        # Container centrale per il profilo
        self.profileContainer = QtWidgets.QWidget(parent=self.main_tab_2)
        self.profileContainer.setMaximumWidth(500)
        self.profileContainerLayout = QtWidgets.QVBoxLayout(
            self.profileContainer)
        self.profileContainerLayout.setContentsMargins(0, 0, 0, 0)
        self.profileContainerLayout.setSpacing(15)

        # Form Layout per info utente
        self.formLayoutProfile = QtWidgets.QFormLayout()
        self.formLayoutProfile.setHorizontalSpacing(20)
        self.formLayoutProfile.setVerticalSpacing(15)
        self.formLayoutProfile.setObjectName("formLayoutProfile")

        # Username
        self.main_slbl_utente = QtWidgets.QLabel(parent=self.profileContainer)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.main_slbl_utente.setFont(font)
        self.main_slbl_utente.setObjectName("main_slbl_utente")

        self.main_dlbl_utente = QtWidgets.QLabel(parent=self.profileContainer)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.main_dlbl_utente.setFont(font)
        self.main_dlbl_utente.setObjectName("main_dlbl_utente")

        self.formLayoutProfile.addRow(
            self.main_slbl_utente, self.main_dlbl_utente)

        # Password row
        self.main_slbl_password = QtWidgets.QLabel(
            parent=self.profileContainer)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.main_slbl_password.setFont(font)
        self.main_slbl_password.setObjectName("main_slbl_password")

        self.main_hlay_pass_tab2 = QtWidgets.QHBoxLayout()
        self.main_hlay_pass_tab2.setSpacing(10)
        self.main_hlay_pass_tab2.setObjectName("main_hlay_pass_tab2")

        self.main_dlbl_password = QtWidgets.QLabel(
            parent=self.profileContainer)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.main_dlbl_password.setFont(font)
        self.main_dlbl_password.setObjectName("main_dlbl_password")
        self.main_hlay_pass_tab2.addWidget(self.main_dlbl_password)

        self.main_btn_visibility_pass = QtWidgets.QPushButton(
            parent=self.profileContainer)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed,
            QtWidgets.QSizePolicy.Policy.Fixed
        )
        self.main_btn_visibility_pass.setSizePolicy(sizePolicy)
        self.main_btn_visibility_pass.setFixedSize(30, 30)
        self.main_btn_visibility_pass.setText("")
        self.main_btn_visibility_pass.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/visible.png"),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.main_btn_visibility_pass.setIcon(icon1)
        self.main_btn_visibility_pass.setObjectName("main_btn_visibility_pass")
        self.main_hlay_pass_tab2.addWidget(self.main_btn_visibility_pass)

        self.main_hlay_pass_tab2.addStretch()

        self.formLayoutProfile.addRow(
            self.main_slbl_password, self.main_hlay_pass_tab2)

        self.profileContainerLayout.addLayout(self.formLayoutProfile)

        # Spacer tra info e bottoni
        spacerProfileBtns = QtWidgets.QSpacerItem(
            20, 30,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Fixed
        )
        self.profileContainerLayout.addItem(spacerProfileBtns)

        # Layout pulsanti
        self.main_hlay_btns_tab2 = QtWidgets.QHBoxLayout()
        self.main_hlay_btns_tab2.setSpacing(15)
        self.main_hlay_btns_tab2.setObjectName("main_hlay_btns_tab2")

        self.main_btn_modutente = QtWidgets.QPushButton(
            parent=self.profileContainer)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.main_btn_modutente.setFont(font)
        self.main_btn_modutente.setMinimumSize(QtCore.QSize(150, 40))
        self.main_btn_modutente.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.main_btn_modutente.setObjectName("main_btn_modutente")
        self.main_hlay_btns_tab2.addWidget(self.main_btn_modutente)

        self.main_btn_logout = QtWidgets.QPushButton(
            parent=self.profileContainer)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.main_btn_logout.setFont(font)
        self.main_btn_logout.setMinimumSize(QtCore.QSize(150, 40))
        self.main_btn_logout.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.main_btn_logout.setObjectName("main_btn_logout")
        self.main_hlay_btns_tab2.addWidget(self.main_btn_logout)

        self.profileContainerLayout.addLayout(self.main_hlay_btns_tab2)

        # Layout per centrare il container
        self.main_hlay_utente_tab2 = QtWidgets.QHBoxLayout()
        self.main_hlay_utente_tab2.setObjectName("main_hlay_utente_tab2")
        self.main_hlay_utente_tab2.addStretch()
        self.main_hlay_utente_tab2.addWidget(self.profileContainer)
        self.main_hlay_utente_tab2.addStretch()

        self.verticalLayout_5.addLayout(self.main_hlay_utente_tab2)

        # Spacer inferiore
        spacerBottomTab2 = QtWidgets.QSpacerItem(
            20, 40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.verticalLayout_5.addItem(spacerBottomTab2)

        self.tabWidget.addTab(self.main_tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(Main)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Gestore Password"))
        self.main_edit_cerca.setPlaceholderText(_translate("Main", "Cerca..."))
        self.main_btn_aggiungi.setText(_translate("Main", "Aggiungi Servizio"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.main_tab1), _translate("Main", "Servizi"))
        self.main_slbl_utente.setText(_translate("Main", "Username:"))
        self.main_dlbl_utente.setText(_translate("Main", ""))
        self.main_slbl_password.setText(_translate("Main", "Password:"))
        self.main_dlbl_password.setText(_translate("Main", "••••••••"))
        self.main_btn_modutente.setText(_translate("Main", "Modifica utente"))
        self.main_btn_logout.setText(_translate("Main", "Log out"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.main_tab_2), _translate("Main", "Profilo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QWidget()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec())
