# Form implementation generated from reading ui file 'ui/ui_modifica_servizio.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Modifica(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(424, 375)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mser_slbl_nuovo_nome = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mser_slbl_nuovo_nome.setFont(font)
        self.mser_slbl_nuovo_nome.setObjectName("mser_slbl_nuovo_nome")
        self.horizontalLayout_2.addWidget(self.mser_slbl_nuovo_nome)
        self.mser_edit_nuovo_nome = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mser_edit_nuovo_nome.setFont(font)
        self.mser_edit_nuovo_nome.setObjectName("mser_edit_nuovo_nome")
        self.horizontalLayout_2.addWidget(self.mser_edit_nuovo_nome)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(17)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mser_slbl_nuovo_user = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mser_slbl_nuovo_user.setFont(font)
        self.mser_slbl_nuovo_user.setObjectName("mser_slbl_nuovo_user")
        self.horizontalLayout_3.addWidget(self.mser_slbl_nuovo_user)
        self.mser_edit_nuovo_user = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mser_edit_nuovo_user.setFont(font)
        self.mser_edit_nuovo_user.setObjectName("mser_edit_nuovo_user")
        self.horizontalLayout_3.addWidget(self.mser_edit_nuovo_user)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(22)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.mser_slbl_nuova_password = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mser_slbl_nuova_password.setFont(font)
        self.mser_slbl_nuova_password.setObjectName("mser_slbl_nuova_password")
        self.horizontalLayout_5.addWidget(self.mser_slbl_nuova_password)
        self.mser_edit_nuova_password = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mser_edit_nuova_password.setFont(font)
        self.mser_edit_nuova_password.setObjectName("mser_edit_nuova_password")
        self.horizontalLayout_5.addWidget(self.mser_edit_nuova_password)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.mser_dlg_btns = QtWidgets.QDialogButtonBox(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mser_dlg_btns.setFont(font)
        self.mser_dlg_btns.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.mser_dlg_btns.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel | QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.mser_dlg_btns.setObjectName("mser_dlg_btns")
        self.verticalLayout.addWidget(self.mser_dlg_btns)

        self.retranslateUi(Dialog)
        self.mser_dlg_btns.accepted.connect(Dialog.accept)  # type: ignore
        self.mser_dlg_btns.rejected.connect(Dialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Modifica servizio"))
        self.mser_slbl_nuovo_nome.setText(_translate("Dialog", "Nuovo nome"))
        self.mser_slbl_nuovo_user.setText(
            _translate("Dialog", "Nuovo username"))
        self.mser_slbl_nuova_password.setText(
            _translate("Dialog", "Nuova Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog_Modifica()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
