# Form implementation generated from reading ui file 'ui/ui_modifica_profilo.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(403, 356)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout.setSpacing(85)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mpro_slbl_utente = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mpro_slbl_utente.setFont(font)
        self.mpro_slbl_utente.setObjectName("mpro_slbl_utente")
        self.horizontalLayout.addWidget(self.mpro_slbl_utente)
        self.mpro_edit_nuovo_utente = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mpro_edit_nuovo_utente.setFont(font)
        self.mpro_edit_nuovo_utente.setObjectName("mpro_edit_nuovo_utente")
        self.horizontalLayout.addWidget(self.mpro_edit_nuovo_utente)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_2.setSpacing(25)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mpro_slbl_vecchia_password = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mpro_slbl_vecchia_password.setFont(font)
        self.mpro_slbl_vecchia_password.setObjectName("mpro_slbl_vecchia_password")
        self.horizontalLayout_2.addWidget(self.mpro_slbl_vecchia_password)
        self.mpro_edit_vecchia_password = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mpro_edit_vecchia_password.setFont(font)
        self.mpro_edit_vecchia_password.setObjectName("mpro_edit_vecchia_password")
        self.horizontalLayout_2.addWidget(self.mpro_edit_vecchia_password)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_3.setSpacing(33)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mpro_slbl_nuova_password = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mpro_slbl_nuova_password.setFont(font)
        self.mpro_slbl_nuova_password.setObjectName("mpro_slbl_nuova_password")
        self.horizontalLayout_3.addWidget(self.mpro_slbl_nuova_password)
        self.mpro_edit_nuova_password = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mpro_edit_nuova_password.setFont(font)
        self.mpro_edit_nuova_password.setObjectName("mpro_edit_nuova_password")
        self.horizontalLayout_3.addWidget(self.mpro_edit_nuova_password)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.mpro_dlg_btns = QtWidgets.QDialogButtonBox(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mpro_dlg_btns.setFont(font)
        self.mpro_dlg_btns.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.mpro_dlg_btns.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.mpro_dlg_btns.setObjectName("mpro_dlg_btns")
        self.verticalLayout_2.addWidget(self.mpro_dlg_btns)

        self.retranslateUi(Dialog)
        self.mpro_dlg_btns.accepted.connect(Dialog.accept) # type: ignore
        self.mpro_dlg_btns.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Modifica Profilo"))
        self.mpro_slbl_utente.setText(_translate("Dialog", "Username"))
        self.mpro_slbl_vecchia_password.setText(_translate("Dialog", "Vecchia password"))
        self.mpro_slbl_nuova_password.setText(_translate("Dialog", "Nuova Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
