# Form implementation generated from reading ui file 'ui/ui_registrati.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Registrazione(object):
    def setupUi(self, Registrazione):
        Registrazione.setObjectName("Registrazione")
        Registrazione.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            Registrazione.sizePolicy().hasHeightForWidth())
        Registrazione.setSizePolicy(sizePolicy)
        Registrazione.setMinimumSize(QtCore.QSize(400, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(Registrazione)
        self.verticalLayout.setObjectName("verticalLayout")
        self.reg_slbl_titolo = QtWidgets.QLabel(parent=Registrazione)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.reg_slbl_titolo.setFont(font)
        self.reg_slbl_titolo.setLayoutDirection(
            QtCore.Qt.LayoutDirection.LeftToRight)
        self.reg_slbl_titolo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.reg_slbl_titolo.setObjectName("reg_slbl_titolo")
        self.verticalLayout.addWidget(self.reg_slbl_titolo)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_4.setSpacing(27)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.reg_slbl_utente = QtWidgets.QLabel(parent=Registrazione)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.reg_slbl_utente.setFont(font)
        self.reg_slbl_utente.setObjectName("reg_slbl_utente")
        self.horizontalLayout_4.addWidget(self.reg_slbl_utente)
        self.reg_edit_utente = QtWidgets.QLineEdit(parent=Registrazione)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.reg_edit_utente.setFont(font)
        self.reg_edit_utente.setObjectName("reg_edit_utente")
        self.horizontalLayout_4.addWidget(self.reg_edit_utente)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reg_slbl_password = QtWidgets.QLabel(parent=Registrazione)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.reg_slbl_password.setFont(font)
        self.reg_slbl_password.setObjectName("reg_slbl_password")
        self.horizontalLayout.addWidget(self.reg_slbl_password)
        self.reg_edit_password = QtWidgets.QLineEdit(parent=Registrazione)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.reg_edit_password.setFont(font)
        self.reg_edit_password.setText("")
        self.reg_edit_password.setObjectName("reg_edit_password")
        self.horizontalLayout.addWidget(self.reg_edit_password)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.reg_btn_crea_utente = QtWidgets.QPushButton(parent=Registrazione)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.reg_btn_crea_utente.setFont(font)
        self.reg_btn_crea_utente.setObjectName("reg_btn_crea_utente")
        self.horizontalLayout_5.addWidget(self.reg_btn_crea_utente)
        self.reg_btn_annulla = QtWidgets.QPushButton(parent=Registrazione)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.reg_btn_annulla.setFont(font)
        self.reg_btn_annulla.setObjectName("reg_btn_annulla")
        self.horizontalLayout_5.addWidget(self.reg_btn_annulla)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Registrazione)
        QtCore.QMetaObject.connectSlotsByName(Registrazione)

    def retranslateUi(self, Registrazione):
        _translate = QtCore.QCoreApplication.translate
        Registrazione.setWindowTitle(_translate("Registrazione", "Form"))
        self.reg_slbl_titolo.setText(_translate("Registrazione", "REGISTRATI"))
        self.reg_slbl_utente.setText(_translate("Registrazione", "Utente"))
        self.reg_slbl_password.setText(_translate("Registrazione", "Password"))
        self.reg_btn_crea_utente.setText(
            _translate("Registrazione", "Crea utente"))
        self.reg_btn_annulla.setText(_translate("Registrazione", "Annulla"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Registrazione = QtWidgets.QWidget()
    ui = Ui_Registrazione()
    ui.setupUi(Registrazione)
    Registrazione.show()
    sys.exit(app.exec())
